services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails server -b 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DEVISE_JWT_SECRET_KEY: 833cea555424ae0681844f0259c7ee31335e630039b0f2048e95200574f2c9e0c5176927d6ec1fa7c10e39dfdcf3495e4e4f7474ff356e35c403c9b2f52eb282

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

volumes:
  postgres_data:
