source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.0'

gem 'rails', "~> 7.2.2", ">= 7.2.2.1"
gem 'puma', '~> 6.0'
gem 'pg', '~> 1.2'
gem 'rack-cors'
gem 'active_storage_validations'
gem 'devise'
gem 'devise-jwt'
gem 'rspec-rails'

